version: 2.1

jobs:
  build:
    machine: true
    steps:
    - run: which docker
    - run: docker -v
    - run: docker build --tag throwaway:$CIRCLE_BUILD_NUM . 
    - run: docker run --rm throwaway:$CIRCLE_BUILD_NUM apt list --installed | grep libmariadb
