version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true
    steps:
    - checkout
    - run: which docker
    - run: docker -v
    - run: docker build --tag throwaway:$CIRCLE_BUILD_NUM . 
    - run: docker run --rm throwaway:$CIRCLE_BUILD_NUM apt list --installed | grep libmariadb
